## 5-1 Split data into training and trade dataset
- Training data split: 2009-01-01 to 2018-12-31
- Trade data split: 2019-01-01 to 2020-09-30

In [ ]:
train = data_split(processed_full, '2009-01-01','2019-01-01')
trade = data_split(processed_full, '2019-01-01','2021-01-01')
# Check the length of the two datasets
print(len(train))
print(len(trade))

109530
21930

In [ ]:
train.head()

        date   tic       open  ...          PE         PB  Div_yield
0 2009-01-02  AAPL   3.067143  ...    0.639733   0.102096   0.000000
0 2009-01-02   AXP  18.570000  ...   50.507629   1.450032   0.011496
0 2009-01-02    BA  42.799999  ...   39.012760 -35.751054   0.012374
0 2009-01-02   CAT  44.910000  ... -171.868997   3.151894   0.012862
0 2009-01-02  CSCO  16.410000  ...   19.850408   1.986886   0.000000

[5 rows x 22 columns]

In [ ]:
trade.head()

        date   tic        open  ...         PE           PB  Div_yield
0 2019-01-01  AAPL   38.722500  ...   5.728691     1.670488   0.019019
0 2019-01-01   AXP   93.910004  ...  50.720114     3.458432   0.004248
0 2019-01-01    BA  316.190002  ...  83.019826  1418.196271   0.006531
0 2019-01-01   CAT  124.029999  ...  35.716285     4.351801   0.007319
0 2019-01-01  CSCO   42.279999  ...  28.011871     4.283841   0.008355

[5 rows x 22 columns]

## 5-2 Set up the training environment

In [ ]:
ratio_list = ['OPM', 'NPM','ROA', 'ROE', 'cur_ratio', 'quick_ratio', 'cash_ratio', 'inv_turnover','acc_rec_turnover', 'acc_pay_turnover', 'debt_ratio', 'debt_to_equity',
       'PE', 'PB', 'Div_yield']

stock_dimension = len(train.tic.unique())
state_space = 1 + 2*stock_dimension + len(ratio_list)*stock_dimension
print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")

Stock Dimension: 30, State Space: 511

In [ ]:
# Parameters for the environment
env_kwargs = {
    "hmax": 100, 
    "initial_amount": 1000000, 
    "buy_cost_pct": 0.001,
    "sell_cost_pct": 0.001,
    "state_space": state_space, 
    "stock_dim": stock_dimension, 
    "tech_indicator_list": ratio_list, 
    "action_space": stock_dimension, 
    "reward_scaling": 1e-4
    
}

#Establish the training environment using StockTradingEnv() class
e_train_gym = StockTradingEnv(df = train, **env_kwargs)

## Environment for Training

In [ ]:
env_train, _ = e_train_gym.get_sb_env()
print(type(env_train))

<class 'stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv'>

<a id='5'></a>
# Part 6: Implement DRL Algorithms

In [ ]:
# Set up the agent using DRLAgent() class using the environment created in the previous part
agent = DRLAgent(env = env_train)

### Model Training: 5 models, A2C DDPG, PPO, TD3, SAC

### Model 1: A2C

In [ ]:
agent = DRLAgent(env = env_train)
model_a2c = agent.get_model("a2c")

{'n_steps': 5, 'ent_coef': 0.01, 'learning_rate': 0.0007}
Using cpu device

In [ ]:
trained_a2c = agent.train_model(model=model_a2c, 
                             tb_log_name='a2c',
                             total_timesteps=100000)

Logging to tensorboard_log/a2c/a2c_1
------------------------------------
| time/                 |          |
|    fps                | 60       |
|    iterations         | 100      |
|    time_elapsed       | 8        |
|    total_timesteps    | 500      |
| train/                |          |
|    entropy_loss       | -42.9    |
|    explained_variance | 0.157    |
|    learning_rate      | 0.0007   |
|    n_updates          | 99       |
|    policy_loss        | 165      |
|    std                | 1.01     |
|    value_loss         | 18.3     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 68       |
|    iterations         | 200      |
|    time_elapsed       | 14       |
|    total_timesteps    | 1000     |
| train/                |          |
|    entropy_loss       | -43      |
|    explained_variance | 0.0513   |
|    learning_rate      | 0.0007   |
|    n_updates          | 199      |
|    policy_loss        | 51.6     |
|    std                | 1.01     |
|    value_loss         | 17.2     |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 71        |
|    iterations         | 300       |
|    time_elapsed       | 20        |
|    total_timesteps    | 1500      |
| train/                |           |
|    entropy_loss       | -42.9     |
|    explained_variance | -1.19e-06 |
|    learning_rate      | 0.0007    |
|    n_updates          | 299       |
|    policy_loss        | -1.03     |
|    std                | 1.01      |
|    value_loss         | 0.541     |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 73       |
|    iterations         | 400      |
|    time_elapsed       | 27       |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -43      |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 399      |
|    policy_loss        | 103      |
|    std                | 1.01     |
|    value_loss         | 5.78     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 74       |
|    iterations         | 500      |
|    time_elapsed       | 33       |
|    total_timesteps    | 2500     |
| train/                |          |
|    entropy_loss       | -43.1    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 499      |
|    policy_loss        | 158      |
|    std                | 1.02     |
|    value_loss         | 23.9     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 74       |
|    iterations         | 600      |
|    time_elapsed       | 40       |
|    total_timesteps    | 3000     |
| train/                |          |
|    entropy_loss       | -43.1    |
|    explained_variance | 5.96e-08 |
|    learning_rate      | 0.0007   |
|    n_updates          | 599      |
|    policy_loss        | 62.7     |
|    std                | 1.02     |
|    value_loss         | 2.76     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 75       |
|    iterations         | 700      |
|    time_elapsed       | 46       |
|    total_timesteps    | 3500     |
| train/                |          |
|    entropy_loss       | -43.1    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 699      |
|    policy_loss        | -136     |
|    std                | 1.02     |
|    value_loss         | 17.3     |
------------------------------------
------------------------------------
| environment/          |          |
|    portfolio_value    | 1.91e+06 |
|    total_cost         | 7.56e+04 |
|    total_reward       | 9.14e+05 |
|    total_reward_pct   | 91.4     |
|    total_trades       | 73316    |
| time/                 |          |
|    fps                | 75       |
|    iterations         | 800      |
|    time_elapsed       | 52       |
|    total_timesteps    | 4000     |
| train/                |          |
|    entropy_loss       | -43.1    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 799      |
|    policy_loss        | -50.6    |
|    std                | 1.02     |
|    value_loss         | 1.55     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 75       |
|    iterations         | 900      |
|    time_elapsed       | 59       |
|    total_timesteps    | 4500     |
| train/                |          |
|    entropy_loss       | -43.2    |
|    explained_variance | 1.79e-07 |
|    learning_rate      | 0.0007   |
|    n_updates          | 899      |
|    policy_loss        | 76.5     |
|    std                | 1.02     |
|    value_loss         | 2.69     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 76       |
|    iterations         | 1000     |
|    time_elapsed       | 65       |
|    total_timesteps    | 5000     |
| train/                |          |
|    entropy_loss       | -43.2    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 999      |
|    policy_loss        | 175      |
|    std                | 1.02     |
|    value_loss         | 17.4     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 76       |
|    iterations         | 1100     |
|    time_elapsed       | 72       |
|    total_timesteps    | 5500     |
| train/                |          |
|    entropy_loss       | -43.2    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 1099     |
|    policy_loss        | -14.7    |
|    std                | 1.02     |
|    value_loss         | 0.158    |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 76       |
|    iterations         | 1200     |
|    time_elapsed       | 78       |
|    total_timesteps    | 6000     |
| train/                |          |
|    entropy_loss       | -43.2    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 1199     |
|    policy_loss        | -84.2    |
|    std                | 1.02     |
|    value_loss         | 3.71     |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 76        |
|    iterations         | 1300      |
|    time_elapsed       | 84        |
|    total_timesteps    | 6500      |
| train/                |           |
|    entropy_loss       | -43.3     |
|    explained_variance | -4.77e-07 |
|    learning_rate      | 0.0007    |
|    n_updates          | 1299      |
|    policy_loss        | -63.5     |
|    std                | 1.02      |
|    value_loss         | 3.31      |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 76       |
|    iterations         | 1400     |
|    time_elapsed       | 91       |
|    total_timesteps    | 7000     |
| train/                |          |
|    entropy_loss       | -43.3    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 1399     |
|    policy_loss        | -309     |
|    std                | 1.03     |
|    value_loss         | 60.1     |
------------------------------------
------------------------------------
| environment/          |          |
|    portfolio_value    | 2.29e+06 |
|    total_cost         | 2.63e+04 |
|    total_reward       | 1.29e+06 |
|    total_reward_pct   | 129      |
|    total_trades       | 60684    |
| time/                 |          |
|    fps                | 76       |
|    iterations         | 1500     |
|    time_elapsed       | 97       |
|    total_timesteps    | 7500     |
| train/                |          |
|    entropy_loss       | -43.4    |
|    explained_variance | -0.33    |
|    learning_rate      | 0.0007   |
|    n_updates          | 1499     |
|    policy_loss        | 61.1     |
|    std                | 1.03     |
|    value_loss         | 3.06     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 76       |
|    iterations         | 1600     |
|    time_elapsed       | 103      |
|    total_timesteps    | 8000     |
| train/                |          |
|    entropy_loss       | -43.5    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 1599     |
|    policy_loss        | -19.4    |
|    std                | 1.03     |
|    value_loss         | 0.955    |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 77        |
|    iterations         | 1700      |
|    time_elapsed       | 110       |
|    total_timesteps    | 8500      |
| train/                |           |
|    entropy_loss       | -43.5     |
|    explained_variance | -1.19e-07 |
|    learning_rate      | 0.0007    |
|    n_updates          | 1699      |
|    policy_loss        | -50.8     |
|    std                | 1.03      |
|    value_loss         | 2.76      |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |
|    iterations         | 1800     |
|    time_elapsed       | 116      |
|    total_timesteps    | 9000     |
| train/                |          |
|    entropy_loss       | -43.5    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 1799     |
|    policy_loss        | 19.4     |
|    std                | 1.03     |
|    value_loss         | 0.647    |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |
|    iterations         | 1900     |
|    time_elapsed       | 123      |
|    total_timesteps    | 9500     |
| train/                |          |
|    entropy_loss       | -43.5    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 1899     |
|    policy_loss        | -187     |
|    std                | 1.03     |
|    value_loss         | 22.8     |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 77        |
|    iterations         | 2000      |
|    time_elapsed       | 129       |
|    total_timesteps    | 10000     |
| train/                |           |
|    entropy_loss       | -43.5     |
|    explained_variance | -1.19e-07 |
|    learning_rate      | 0.0007    |
|    n_updates          | 1999      |
|    policy_loss        | -71.4     |
|    std                | 1.03      |
|    value_loss         | 4.75      |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |
|    iterations         | 2100     |
|    time_elapsed       | 135      |
|    total_timesteps    | 10500    |
| train/                |          |
|    entropy_loss       | -43.5    |
|    explained_variance | 5.96e-08 |
|    learning_rate      | 0.0007   |
|    n_updates          | 2099     |
|    policy_loss        | 73.2     |
|    std                | 1.03     |
|    value_loss         | 4.46     |
------------------------------------
------------------------------------
| environment/          |          |
|    portfolio_value    | 4.38e+06 |
|    total_cost         | 3.17e+04 |
|    total_reward       | 3.38e+06 |
|    total_reward_pct   | 338      |
|    total_trades       | 65214    |
| time/                 |          |
|    fps                | 77       |
|    iterations         | 2200     |
|    time_elapsed       | 142      |
|    total_timesteps    | 11000    |
| train/                |          |
|    entropy_loss       | -43.7    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 2199     |
|    policy_loss        | -37.4    |
|    std                | 1.04     |
|    value_loss         | 1.05     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |
|    iterations         | 2300     |
|    time_elapsed       | 148      |
|    total_timesteps    | 11500    |
| train/                |          |
|    entropy_loss       | -43.7    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 2299     |
|    policy_loss        | -52.1    |
|    std                | 1.04     |
|    value_loss         | 2.56     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |
|    iterations         | 2400     |
|    time_elapsed       | 155      |
|    total_timesteps    | 12000    |
| train/                |          |
|    entropy_loss       | -43.7    |
|    explained_variance | 5.96e-08 |
|    learning_rate      | 0.0007   |
|    n_updates          | 2399     |
|    policy_loss        | -91.9    |
|    std                | 1.04     |
|    value_loss         | 6.52     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |
|    iterations         | 2500     |
|    time_elapsed       | 161      |
|    total_timesteps    | 12500    |
| train/                |          |
|    entropy_loss       | -43.7    |
|    explained_variance | 1.19e-07 |
|    learning_rate      | 0.0007   |
|    n_updates          | 2499     |
|    policy_loss        | 19.6     |
|    std                | 1.04     |
|    value_loss         | 0.766    |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |
|    iterations         | 2600     |
|    time_elapsed       | 167      |
|    total_timesteps    | 13000    |
| train/                |          |
|    entropy_loss       | -43.7    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 2599     |
|    policy_loss        | -58.4    |
|    std                | 1.04     |
|    value_loss         | 2.59     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |
|    iterations         | 2700     |
|    time_elapsed       | 174      |
|    total_timesteps    | 13500    |
| train/                |          |
|    entropy_loss       | -43.8    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 2699     |
|    policy_loss        | -177     |
|    std                | 1.04     |
|    value_loss         | 24.6     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |
|    iterations         | 2800     |
|    time_elapsed       | 180      |
|    total_timesteps    | 14000    |
| train/                |          |
|    entropy_loss       | -43.8    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 2799     |
|    policy_loss        | 54.1     |
|    std                | 1.04     |
|    value_loss         | 1.96     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |
|    iterations         | 2900     |
|    time_elapsed       | 187      |
|    total_timesteps    | 14500    |
| train/                |          |
|    entropy_loss       | -43.8    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 2899     |
|    policy_loss        | 127      |
|    std                | 1.04     |
|    value_loss         | 15.7     |
------------------------------------
------------------------------------
| environment/          |          |
|    portfolio_value    | 2.92e+06 |
|    total_cost         | 1.85e+04 |
|    total_reward       | 1.92e+06 |
|    total_reward_pct   | 192      |
|    total_trades       | 67453    |
| time/                 |          |
|    fps                | 77       |
|    iterations         | 3000     |
|    time_elapsed       | 193      |
|    total_timesteps    | 15000    |
| train/                |          |
|    entropy_loss       | -43.8    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 2999     |
|    policy_loss        | -97.9    |
|    std                | 1.04     |
|    value_loss         | 5.52     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |
|    iterations         | 3100     |
|    time_elapsed       | 199      |
|    total_timesteps    | 15500    |
| train/                |          |
|    entropy_loss       | -43.9    |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 3099     |
|    policy_loss        | -87.5    |
|    std                | 1.05     |
|    value_loss         | 4.94     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |
|    iterations         | 3200     |
|    time_elapsed       | 206      |
|    total_timesteps    | 16000    |
| train/                |          |
|    entropy_loss       | -44      |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 3199     |
|    policy_loss        | -199     |
|    std                | 1.05     |
|    value_loss         | 21.3     |
------------------------------------
-------------------------------------
| time/                 |           |
|    fps                | 77        |
|    iterations         | 3300      |
|    time_elapsed       | 212       |
|    total_timesteps    | 16500     |
| train/                |           |
|    entropy_loss       | -44       |
|    explained_variance | -3.58e-07 |
|    learning_rate      | 0.0007    |
|    n_updates          | 3299      |
|    policy_loss        | 59.4      |
|    std                | 1.05      |
|    value_loss         | 4.14      |
-------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |
|    iterations         | 3400     |
|    time_elapsed       | 219      |
|    total_timesteps    | 17000    |
| train/                |          |
|    entropy_loss       | -44      |
|    explained_variance | 0        |
|    learning_rate      | 0.0007   |
|    n_updates          | 3399     |
|    policy_loss        | -32.7    |
|    std                | 1.05     |
|    value_loss         | 1.65     |
------------------------------------
------------------------------------
| time/                 |          |
|    fps                | 77       |

### Model 2: DDPG

In [ ]:
agent = DRLAgent(env = env_train)
model_ddpg = agent.get_model("ddpg")

{'batch_size': 128, 'buffer_size': 50000, 'learning_rate': 0.001}
Using cuda device

In [ ]:
trained_ddpg = agent.train_model(model=model_ddpg, 
                             tb_log_name='ddpg',
                             total_timesteps=50000)

Logging to tensorboard_log/ddpg/ddpg_3
---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 66       |
|    time_elapsed    | 218      |
|    total timesteps | 14604    |
| train/             |          |
|    actor_loss      | -40.1    |
|    critic_loss     | 213      |
|    learning_rate   | 0.001    |
|    n_updates       | 10953    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 62       |
|    time_elapsed    | 463      |
|    total timesteps | 29208    |
| train/             |          |
|    actor_loss      | -14.9    |
|    critic_loss     | 2.92     |
|    learning_rate   | 0.001    |
|    n_updates       | 25557    |
---------------------------------
day: 3650, episode: 40
begin_total_asset: 1000000.00
end_total_asset: 3024712.17
total_reward: 2024712.17
total_cost: 999.00
total_trades: 72983
Sharpe: 0.626
=================================
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 61       |
|    time_elapsed    | 710      |
|    total timesteps | 43812    |
| train/             |          |
|    actor_loss      | -10.4    |
|    critic_loss     | 2.28     |
|    learning_rate   | 0.001    |
|    n_updates       | 40161    |
---------------------------------

### Model 3: PPO

In [ ]:
agent = DRLAgent(env = env_train)
PPO_PARAMS = {
    "n_steps": 2048,
    "ent_coef": 0.01,
    "learning_rate": 0.00025,
    "batch_size": 128,
}
model_ppo = agent.get_model("ppo",model_kwargs = PPO_PARAMS)

{'n_steps': 2048, 'ent_coef': 0.01, 'learning_rate': 0.00025, 'batch_size': 128}
Using cpu device

In [ ]:
trained_ppo = agent.train_model(model=model_ppo, 
                             tb_log_name='ppo',
                             total_timesteps=50000)

Logging to tensorboard_log/ppo/ppo_1
-----------------------------
| time/              |      |
|    fps             | 76   |
|    iterations      | 1    |
|    time_elapsed    | 26   |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 75          |
|    iterations           | 2           |
|    time_elapsed         | 54          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.018077655 |
|    clip_fraction        | 0.231       |
|    clip_range           | 0.2         |
|    entropy_loss         | -42.6       |
|    explained_variance   | -0.0123     |
|    learning_rate        | 0.00025     |
|    loss                 | 3.1         |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0292     |
|    std                  | 1           |
|    value_loss           | 7.21        |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 75          |
|    iterations           | 3           |
|    time_elapsed         | 81          |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.013950874 |
|    clip_fraction        | 0.17        |
|    clip_range           | 0.2         |
|    entropy_loss         | -42.6       |
|    explained_variance   | -0.00143    |
|    learning_rate        | 0.00025     |
|    loss                 | 5.92        |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0229     |
|    std                  | 1           |
|    value_loss           | 13.6        |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 74         |
|    iterations           | 4          |
|    time_elapsed         | 109        |
|    total_timesteps      | 8192       |
| train/                  |            |
|    approx_kl            | 0.01641549 |
|    clip_fraction        | 0.183      |
|    clip_range           | 0.2        |
|    entropy_loss         | -42.6      |
|    explained_variance   | -0.0118    |
|    learning_rate        | 0.00025    |
|    loss                 | 6.06       |
|    n_updates            | 30         |
|    policy_gradient_loss | -0.0282    |
|    std                  | 1          |
|    value_loss           | 11.9       |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 74          |
|    iterations           | 5           |
|    time_elapsed         | 136         |
|    total_timesteps      | 10240       |
| train/                  |             |
|    approx_kl            | 0.025979618 |
|    clip_fraction        | 0.241       |
|    clip_range           | 0.2         |
|    entropy_loss         | -42.7       |
|    explained_variance   | -0.00485    |
|    learning_rate        | 0.00025     |
|    loss                 | 13          |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0157     |
|    std                  | 1           |
|    value_loss           | 19.3        |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 74          |
|    iterations           | 6           |
|    time_elapsed         | 163         |
|    total_timesteps      | 12288       |
| train/                  |             |
|    approx_kl            | 0.016590398 |
|    clip_fraction        | 0.21        |
|    clip_range           | 0.2         |
|    entropy_loss         | -42.7       |
|    explained_variance   | -0.0153     |
|    learning_rate        | 0.00025     |
|    loss                 | 3.53        |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0251     |
|    std                  | 1.01        |
|    value_loss           | 11          |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 74          |
|    iterations           | 7           |
|    time_elapsed         | 191         |
|    total_timesteps      | 14336       |
| train/                  |             |
|    approx_kl            | 0.020591479 |
|    clip_fraction        | 0.229       |
|    clip_range           | 0.2         |
|    entropy_loss         | -42.8       |
|    explained_variance   | 0.0132      |
|    learning_rate        | 0.00025     |
|    loss                 | 6.55        |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0197     |
|    std                  | 1.01        |
|    value_loss           | 14.2        |
-----------------------------------------
day: 3650, episode: 20
begin_total_asset: 1000000.00
end_total_asset: 2689089.43
total_reward: 1689089.43
total_cost: 380034.51
total_trades: 104033
Sharpe: 0.638
=================================
-----------------------------------------
| time/                   |             |
|    fps                  | 74          |
|    iterations           | 8           |
|    time_elapsed         | 218         |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.020969098 |
|    clip_fraction        | 0.268       |
|    clip_range           | 0.2         |
|    entropy_loss         | -42.9       |
|    explained_variance   | -0.000622   |
|    learning_rate        | 0.00025     |
|    loss                 | 7           |
|    n_updates            | 70          |
|    policy_gradient_loss | -0.0173     |
|    std                  | 1.01        |
|    value_loss           | 12.7        |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 74         |
|    iterations           | 9          |
|    time_elapsed         | 246        |
|    total_timesteps      | 18432      |
| train/                  |            |
|    approx_kl            | 0.02511882 |
|    clip_fraction        | 0.28       |
|    clip_range           | 0.2        |
|    entropy_loss         | -43        |
|    explained_variance   | -0.0182    |
|    learning_rate        | 0.00025    |
|    loss                 | 5.87       |
|    n_updates            | 80         |
|    policy_gradient_loss | -0.0152    |
|    std                  | 1.02       |
|    value_loss           | 11.4       |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 74         |
|    iterations           | 10         |
|    time_elapsed         | 273        |
|    total_timesteps      | 20480      |
| train/                  |            |
|    approx_kl            | 0.02978786 |
|    clip_fraction        | 0.276      |
|    clip_range           | 0.2        |
|    entropy_loss         | -43.1      |
|    explained_variance   | 0.00553    |
|    learning_rate        | 0.00025    |
|    loss                 | 7.83       |
|    n_updates            | 90         |
|    policy_gradient_loss | -0.0169    |
|    std                  | 1.02       |
|    value_loss           | 18         |
----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 74         |
|    iterations           | 11         |
|    time_elapsed         | 301        |
|    total_timesteps      | 22528      |
| train/                  |            |
|    approx_kl            | 0.02986148 |
|    clip_fraction        | 0.263      |
|    clip_range           | 0.2        |
|    entropy_loss         | -43.1      |
|    explained_variance   | -0.0465    |
|    learning_rate        | 0.00025    |
|    loss                 | 4.94       |
|    n_updates            | 100        |
|    policy_gradient_loss | -0.0156    |
|    std                  | 1.02       |
|    value_loss           | 9.13       |
----------------------------------------
---------------------------------------
| time/                   |           |
|    fps                  | 74        |
|    iterations           | 12        |
|    time_elapsed         | 328       |
|    total_timesteps      | 24576     |
| train/                  |           |
|    approx_kl            | 0.0287299 |
|    clip_fraction        | 0.267     |
|    clip_range           | 0.2       |
|    entropy_loss         | -43.2     |
|    explained_variance   | -0.00762  |
|    learning_rate        | 0.00025   |
|    loss                 | 9.6       |
|    n_updates            | 110       |
|    policy_gradient_loss | -0.0165   |
|    std                  | 1.02      |
|    value_loss           | 20.9      |
---------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 74          |
|    iterations           | 13          |
|    time_elapsed         | 355         |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.023247771 |
|    clip_fraction        | 0.264       |
|    clip_range           | 0.2         |
|    entropy_loss         | -43.2       |
|    explained_variance   | -0.0257     |
|    learning_rate        | 0.00025     |
|    loss                 | 2.04        |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.0105     |
|    std                  | 1.02        |
|    value_loss           | 6.91        |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 74          |
|    iterations           | 14          |
|    time_elapsed         | 382         |
|    total_timesteps      | 28672       |
| train/                  |             |
|    approx_kl            | 0.020957708 |
|    clip_fraction        | 0.243       |
|    clip_range           | 0.2         |
|    entropy_loss         | -43.3       |
|    explained_variance   | -0.00506    |
|    learning_rate        | 0.00025     |
|    loss                 | 3.57        |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.0166     |
|    std                  | 1.02        |
|    value_loss           | 11.4        |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 74          |
|    iterations           | 15          |
|    time_elapsed         | 410         |
|    total_timesteps      | 30720       |
| train/                  |             |
|    approx_kl            | 0.032833345 |
|    clip_fraction        | 0.296       |
|    clip_range           | 0.2         |
|    entropy_loss         | -43.4       |
|    explained_variance   | -0.0181     |
|    learning_rate        | 0.00025     |
|    loss                 | 2.71        |
|    n_updates            | 140         |
|    policy_gradient_loss | -0.0192     |
|    std                  | 1.03        |
|    value_loss           | 7.09        |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 74         |
|    iterations           | 16         |
|    time_elapsed         | 437        |
|    total_timesteps      | 32768      |
| train/                  |            |
|    approx_kl            | 0.02443498 |
|    clip_fraction        | 0.241      |
|    clip_range           | 0.2        |
|    entropy_loss         | -43.5      |
|    explained_variance   | -0.0293    |
|    learning_rate        | 0.00025    |
|    loss                 | 4.9        |
|    n_updates            | 150        |
|    policy_gradient_loss | -0.0277    |
|    std                  | 1.03       |
|    value_loss           | 8.48       |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 74          |
|    iterations           | 17          |
|    time_elapsed         | 464         |
|    total_timesteps      | 34816       |
| train/                  |             |
|    approx_kl            | 0.016761096 |
|    clip_fraction        | 0.233       |
|    clip_range           | 0.2         |
|    entropy_loss         | -43.5       |
|    explained_variance   | -0.0188     |
|    learning_rate        | 0.00025     |
|    loss                 | 3           |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.0162     |
|    std                  | 1.03        |
|    value_loss           | 9.8         |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 74         |
|    iterations           | 18         |
|    time_elapsed         | 491        |
|    total_timesteps      | 36864      |
| train/                  |            |
|    approx_kl            | 0.03664797 |
|    clip_fraction        | 0.34       |
|    clip_range           | 0.2        |
|    entropy_loss         | -43.6      |
|    explained_variance   | 0.00438    |
|    learning_rate        | 0.00025    |
|    loss                 | 4.71       |
|    n_updates            | 170        |
|    policy_gradient_loss | -0.0206    |
|    std                  | 1.04       |
|    value_loss           | 6.72       |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 74          |
|    iterations           | 19          |
|    time_elapsed         | 518         |
|    total_timesteps      | 38912       |
| train/                  |             |
|    approx_kl            | 0.030327313 |
|    clip_fraction        | 0.308       |
|    clip_range           | 0.2         |
|    entropy_loss         | -43.6       |
|    explained_variance   | 0.0309      |
|    learning_rate        | 0.00025     |
|    loss                 | 6           |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.00991    |
|    std                  | 1.04        |
|    value_loss           | 11.2        |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 75          |
|    iterations           | 20          |
|    time_elapsed         | 545         |
|    total_timesteps      | 40960       |
| train/                  |             |
|    approx_kl            | 0.028725432 |
|    clip_fraction        | 0.244       |
|    clip_range           | 0.2         |
|    entropy_loss         | -43.7       |
|    explained_variance   | 0.0224      |
|    learning_rate        | 0.00025     |
|    loss                 | 1.66        |
|    n_updates            | 190         |
|    policy_gradient_loss | -0.00988    |
|    std                  | 1.04        |
|    value_loss           | 6.45        |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 75          |
|    iterations           | 21          |
|    time_elapsed         | 573         |
|    total_timesteps      | 43008       |
| train/                  |             |
|    approx_kl            | 0.035785355 |
|    clip_fraction        | 0.252       |
|    clip_range           | 0.2         |
|    entropy_loss         | -43.8       |
|    explained_variance   | -0.00199    |
|    learning_rate        | 0.00025     |
|    loss                 | 7.69        |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.00915    |
|    std                  | 1.04        |
|    value_loss           | 14.2        |
-----------------------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 75         |
|    iterations           | 22         |
|    time_elapsed         | 600        |
|    total_timesteps      | 45056      |
| train/                  |            |
|    approx_kl            | 0.02488321 |
|    clip_fraction        | 0.259      |
|    clip_range           | 0.2        |
|    entropy_loss         | -43.8      |
|    explained_variance   | 0.0224     |
|    learning_rate        | 0.00025    |
|    loss                 | 3.55       |
|    n_updates            | 210        |
|    policy_gradient_loss | -0.00496   |
|    std                  | 1.04       |
|    value_loss           | 8.94       |
----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 75          |
|    iterations           | 23          |
|    time_elapsed         | 627         |
|    total_timesteps      | 47104       |
| train/                  |             |
|    approx_kl            | 0.024153344 |
|    clip_fraction        | 0.272       |
|    clip_range           | 0.2         |
|    entropy_loss         | -43.9       |
|    explained_variance   | -0.0405     |
|    learning_rate        | 0.00025     |
|    loss                 | 5.38        |
|    n_updates            | 220         |
|    policy_gradient_loss | -0.0153     |
|    std                  | 1.05        |
|    value_loss           | 14.4        |
-----------------------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 75          |
|    iterations           | 24          |
|    time_elapsed         | 654         |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.037768982 |
|    clip_fraction        | 0.309       |
|    clip_range           | 0.2         |
|    entropy_loss         | -44         |
|    explained_variance   | -0.00958    |
|    learning_rate        | 0.00025     |
|    loss                 | 4.37        |
|    n_updates            | 230         |
|    policy_gradient_loss | 0.00366     |
|    std                  | 1.05        |
|    value_loss           | 12.4        |
-----------------------------------------
day: 3650, episode: 30
begin_total_asset: 1000000.00
end_total_asset: 3250700.91
total_reward: 2250700.91
total_cost: 329606.76
total_trades: 98701
Sharpe: 0.750
=================================
-----------------------------------------
| time/                   |             |
|    fps                  | 75          |
|    iterations           | 25          |
|    time_elapsed         | 681         |
|    total_timesteps      | 51200       |
| train/                  |             |
|    approx_kl            | 0.034196474 |
|    clip_fraction        | 0.301       |
|    clip_range           | 0.2         |
|    entropy_loss         | -44.1       |
|    explained_variance   | -0.00227    |
|    learning_rate        | 0.00025     |
|    loss                 | 3.84        |
|    n_updates            | 240         |
|    policy_gradient_loss | -0.0192     |
|    std                  | 1.05        |
|    value_loss           | 11.4        |
-----------------------------------------

### Model 4: TD3

In [ ]:
agent = DRLAgent(env = env_train)
TD3_PARAMS = {"batch_size": 100, 
              "buffer_size": 1000000, 
              "learning_rate": 0.001}

model_td3 = agent.get_model("td3",model_kwargs = TD3_PARAMS)

{'batch_size': 100, 'buffer_size': 1000000, 'learning_rate': 0.001}
Using cpu device

In [ ]:
trained_td3 = agent.train_model(model=model_td3, 
                             tb_log_name='td3',
                             total_timesteps=30000)

Logging to tensorboard_log/td3/td3_1
---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 26       |
|    time_elapsed    | 559      |
|    total timesteps | 14604    |
| train/             |          |
|    actor_loss      | 4.64     |
|    critic_loss     | 720      |
|    learning_rate   | 0.001    |
|    n_updates       | 10953    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 22       |
|    time_elapsed    | 1289     |
|    total timesteps | 29208    |
| train/             |          |
|    actor_loss      | 10.6     |
|    critic_loss     | 14.2     |
|    learning_rate   | 0.001    |
|    n_updates       | 25557    |
---------------------------------
day: 3650, episode: 40
begin_total_asset: 1000000.00
end_total_asset: 3319811.55
total_reward: 2319811.55
total_cost: 998.99
total_trades: 51100
Sharpe: 0.649
=================================

### Model 5: SAC

In [ ]:
agent = DRLAgent(env = env_train)
SAC_PARAMS = {
    "batch_size": 128,
    "buffer_size": 1000000,
    "learning_rate": 0.0001,
    "learning_starts": 100,
    "ent_coef": "auto_0.1",
}

model_sac = agent.get_model("sac",model_kwargs = SAC_PARAMS)

{'batch_size': 128, 'buffer_size': 1000000, 'learning_rate': 0.0001, 'learning_starts': 100, 'ent_coef': 'auto_0.1'}
Using cpu device

In [ ]:
trained_sac = agent.train_model(model=model_sac, 
                             tb_log_name='sac',
                             total_timesteps=80000)

Logging to tensorboard_log/sac/sac_2
---------------------------------
| time/              |          |
|    episodes        | 4        |
|    fps             | 21       |
|    time_elapsed    | 685      |
|    total timesteps | 14604    |
| train/             |          |
|    actor_loss      | 172      |
|    critic_loss     | 28.6     |
|    ent_coef        | 0.0742   |
|    ent_coef_loss   | -126     |
|    learning_rate   | 0.0001   |
|    n_updates       | 14503    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 8        |
|    fps             | 20       |
|    time_elapsed    | 1401     |
|    total timesteps | 29208    |
| train/             |          |
|    actor_loss      | 9.68     |
|    critic_loss     | 9.81     |
|    ent_coef        | 0.0174   |
|    ent_coef_loss   | -173     |
|    learning_rate   | 0.0001   |
|    n_updates       | 29107    |
---------------------------------
day: 3650, episode: 10
begin_total_asset: 1000000.00
end_total_asset: 4889674.97
total_reward: 3889674.97
total_cost: 7706.97
total_trades: 70158
Sharpe: 0.752
=================================
---------------------------------
| time/              |          |
|    episodes        | 12       |
|    fps             | 20       |
|    time_elapsed    | 2114     |
|    total timesteps | 43812    |
| train/             |          |
|    actor_loss      | -13.3    |
|    critic_loss     | 14       |
|    ent_coef        | 0.00427  |
|    ent_coef_loss   | -128     |
|    learning_rate   | 0.0001   |
|    n_updates       | 43711    |
---------------------------------
---------------------------------
| time/              |          |
|    episodes        | 16       |
|    fps             | 20       |
|    time_elapsed    | 2842     |
|    total timesteps | 58416    |
| train/             |          |
|    actor_loss      | -7       |
|    critic_loss     | 8.71     |
|    ent_coef        | 0.00148  |
|    ent_coef_loss   | -3.87    |
|    learning_rate   | 0.0001   |
|    n_updates       | 58315    |
---------------------------------
day: 3650, episode: 20
begin_total_asset: 1000000.00
end_total_asset: 3389166.27
total_reward: 2389166.27
total_cost: 1895.61
total_trades: 62481
Sharpe: 0.623
=================================
---------------------------------
| time/              |          |
|    episodes        | 20       |
|    fps             | 20       |
|    time_elapsed    | 3585     |
|    total timesteps | 73020    |
| train/             |          |
|    actor_loss      | -4.82    |
|    critic_loss     | 12.4     |
|    ent_coef        | 0.00159  |
|    ent_coef_loss   | -4.38    |
|    learning_rate   | 0.0001   |
|    n_updates       | 72919    |
---------------------------------

### Trade

In [ ]:
trade = data_split(processed_full, '2019-01-01','2021-01-01')
e_trade_gym = StockTradingEnv(df = trade, **env_kwargs)
# env_trade, obs_trade = e_trade_gym.get_sb_env()

In [ ]:
trade.head()

        date   tic        open  ...         PE           PB  Div_yield
0 2019-01-01  AAPL   38.722500  ...   5.728691     1.670488   0.019019
0 2019-01-01   AXP   93.910004  ...  50.720114     3.458432   0.004248
0 2019-01-01    BA  316.190002  ...  83.019826  1418.196271   0.006531
0 2019-01-01   CAT  124.029999  ...  35.716285     4.351801   0.007319
0 2019-01-01  CSCO   42.279999  ...  28.011871     4.283841   0.008355

[5 rows x 22 columns]

In [ ]:
df_account_value, df_actions = DRLAgent.DRL_prediction(
    model=trained_ddpg, 
    environment = e_trade_gym)

hit end!

In [ ]:
df_account_value.shape

(731, 2)

In [ ]:
df_account_value.tail()

          date  account_value
726 2020-12-27   1.338573e+06
727 2020-12-28   1.338573e+06
728 2020-12-29   1.334876e+06
729 2020-12-30   1.340975e+06
730 2020-12-31   1.350643e+06

In [ ]:
df_actions.head()

            AAPL  AXP  BA  CAT  CSCO  CVX  ...  UNH    V   VZ  WBA  WMT  XOM
date                                       ...
2019-01-01     0    0   0  100   100    0  ...    0  100  100  100  100    0
2019-01-02     0    0   0  100   100    0  ...    0  100  100  100  100    0
2019-01-03     0    0   0  100   100    0  ...    0  100  100  100  100    0
2019-01-04     0    0   0  100   100    0  ...    0  100  100  100  100    0
2019-01-05     0    0   0  100   100    0  ...    0  100  100  100  100    0

[5 rows x 30 columns]

<a id='6'></a>
# Part 7: Backtest Our Strategy

<a id='6.1'></a>
## 7.1 BackTestStats
pass in df_account_value, this information is stored in env class

In [ ]:
print("==============Get Backtest Results===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value)
perf_stats_all = pd.DataFrame(perf_stats_all)
perf_stats_all.to_csv("./"+config.RESULTS_DIR+"/perf_stats_all_"+now+'.csv')

==============Get Backtest Results===========
Annual return          0.109179
Cumulative returns     0.350643
Annual volatility      0.210154
Sharpe ratio           0.599338
Calmar ratio           0.339833
Stability              0.296554
Max drawdown          -0.321272
Omega ratio            1.164859
Sortino ratio          0.841479
Skew                        NaN
Kurtosis                    NaN
Tail ratio             0.899170
Daily value at risk   -0.025977
dtype: float64

In [ ]:
#baseline stats
print("==============Get Baseline Stats===========")
baseline_df = get_baseline(
        ticker="^DJI", 
        start = '2019-01-01',
        end = '2021-01-01')

stats = backtest_stats(baseline_df, value_col_name = 'close')

==============Get Baseline Stats===========
[*********************100%***********************]  1 of 1 completed
Shape of DataFrame:  (505, 8)
Annual return          0.144674
Cumulative returns     0.310981
Annual volatility      0.274619
Sharpe ratio           0.631418
Calmar ratio           0.390102
Stability              0.116677
Max drawdown          -0.370862
Omega ratio            1.149365
Sortino ratio          0.870084
Skew                        NaN
Kurtosis                    NaN
Tail ratio             0.860710
Daily value at risk   -0.033911
dtype: float64

<a id='6.2'></a>
## 7.2 BackTestPlot